version: '3.9'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017
    volumes:
      - ./dist/containers/mongo:/data/db
  app:
    depends_on:
      - monogdb
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - MONGO_DB_URI=mongodb://mongodb/timo
    stdin_open: true
    tty: true