openapi: 3.0.0
info:
  title: Time Tracking API
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000'
paths:
  '/{userId}/log':
    post:
      summary: Timeblocks
      operationId: log-time
      description: Start logging a time
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeEntry'
            examples: {}
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    delete:
      summary: ''
      operationId: discard-timelog
      responses:
        '200':
          description: OK
      description: Discard currently logged time
    put:
      summary: ''
      operationId: stop-timelog
      responses:
        '200':
          description: OK
      description: Update (stop) current time session.
  '/{userId}/summary':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
    get:
      summary: Generate weekly summary
      tags: []
      responses: {}
      operationId: get-userId-summary
      description: Provides .csv file with timesheet from past week.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sum:
                  type: object
                  properties:
                    monday:
                      type: string
                    tuesday:
                      type: string
                    '':
                      type: string
                fromDate:
                  type: string
                toDate:
                  type: string
                file:
                  type: string
    post:
      summary: Get summary from specific timeframe
      operationId: post-userId-summary
      responses:
        '200':
          description: OK
      description: ''
  /users:
    get:
      summary: Get users from database
      tags: []
      responses: {}
      operationId: get-users
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/User'
            examples: {}
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples: {}
      properties:
        _id:
          type: string
          description: Unique identifier for the given user.
          format: uuid
        nickname:
          type: string
          example: Jay
      required:
        - nickname
    TimeEntry:
      title: TimeEntry
      type: object
      description: ''
      properties:
        _id:
          type: string
          format: uuid
        user:
          $ref: '#/components/schemas/User'
        isTracking:
          type: boolean
        description:
          type: string
        startedAt:
          type: string
        endedAt:
          type: string
      required:
        - user
        - isTracking
        - startedAt
