openapi: 3.0.0
info:
  title: Time Tracking API
  version: '2.1'
  description: API for a small application commissioned for me as a recruitment task by Nextrope. The purpose of the application is to use TypeScript and any HTTP application framework to create a solution that will allow us to track time and generate reports on how much time we spent working on a given day.
  contact:
    name: Jay Whitewood
    url: 'https://github.com/keinsell'
    email: keinsell@protonmail.com
  license:
    name: MIT
    url: 'https://github.com/keinsell/timo/blob/main/LICENSE'
servers:
  - url: 'http://localhost:1337'
    description: local
  - description: staging
    url: 'https://a68f86c.herokuapp.com'
paths:
  /u:
    get:
      summary: Check users from database
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    data:
                      - jay
                properties:
                  data:
                    type: array
                    items:
                      type: string
                required:
                  - data
              examples: {}
        '':
          description: API always will return array with usernames of registred users.
      operationId: get-users
      description: Get an array of usernames found in database.
    post:
      summary: Create new user
      operationId: post-users
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/User'
        '409':
          description: Conflict
      description: Creates new user in database.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: jay
              required:
                - username
        description: ''
    parameters: []
  '/u/{username}':
    parameters:
      - schema:
          type: string
          example: jay
        name: username
        in: path
        required: true
        description: jay
    delete:
      summary: ''
      operationId: delete-u-username
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
      description: Delete specific username from database.
  '/t/{username}':
    parameters:
      - schema:
          type: string
          example: jay
        name: username
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    timeblock:
                      _id: 61ee8c7cdbe4f2f3de64fc8a
                      user: jay
                      isTracking: true
                      createdAt: '2022-01-24T11:24:44.156Z'
                      __v: 0
                      duration: 5h
                    archive:
                      - _id: 61ee8c7cdbe4f2f3de64fc8a
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:24:44.156Z'
                        __v: 0
                        duration: 5h
                      - _id: 61ee8d13c33e39c0bc2dc768
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:15.411Z'
                        __v: 0
                        description: Designing website
                      - _id: 61ee8d15c33e39c0bc2dc76c
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:17.052Z'
                        __v: 0
                        description: Designing website
                      - _id: 61ee8d15c33e39c0bc2dc770
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:17.584Z'
                        __v: 0
                        description: Designing website
                      - _id: 61ee8d16c33e39c0bc2dc774
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:18.106Z'
                        __v: 0
                        description: Designing website
                properties:
                  timeblock:
                    $ref: '#/components/schemas/TimeEntry'
                  archive:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      $ref: '#/components/schemas/TimeEntry'
                required:
                  - archive
              examples:
                When there is running timeblock:
                  value:
                    timeblock:
                      _id: 61ee8c7cdbe4f2f3de64fc8a
                      user: jay
                      isTracking: true
                      createdAt: '2022-01-24T11:24:44.156Z'
                      __v: 0
                      duration: 5h
                    archive:
                      - _id: 61ee8c7cdbe4f2f3de64fc8a
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:24:44.156Z'
                        __v: 0
                        duration: 5h
                      - _id: 61ee8d13c33e39c0bc2dc768
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:15.411Z'
                        __v: 0
                        description: Designing website
                      - _id: 61ee8d15c33e39c0bc2dc76c
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:17.052Z'
                        __v: 0
                        description: Designing website
                      - _id: 61ee8d15c33e39c0bc2dc770
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:17.584Z'
                        __v: 0
                        description: Designing website
                      - _id: 61ee8d16c33e39c0bc2dc774
                        user: jay
                        isTracking: true
                        createdAt: '2022-01-24T11:27:18.106Z'
                        __v: 0
                        description: Designing website
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  status:
                    type: string
                    minLength: 1
                required:
                  - status
                x-examples:
                  example-1:
                    status: No active timeblock found
              examples:
                No Timeblock:
                  value:
                    status: No active timeblock found
                No User:
                  value:
                    status: User not found
      operationId: get-t-username
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeEntry'
            examples:
              Start a new timeblock:
                value:
                  description: Designing a new webpage.
              Add passed timeblock:
                value:
                  isTracking: false
                  createdAt: '2019-08-24T14:15:22Z'
                  endedAt: '2019-08-24T14:15:22Z'
                  description: Designing website for law company.
        description: ''
    post:
      summary: ''
      operationId: post-t-username
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                  example: Designing website
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples: {}
      properties:
        _id:
          type: string
          description: Unique identifier for the given user.
          format: uuid
        nickname:
          type: string
          example: Jay
      required:
        - nickname
    TimeEntry:
      title: Timeblock
      type: object
      description: Database model that holds information about single Timeblock.
      properties:
        _id:
          type: string
          format: uuid
        user:
          type: string
          example: jay
        isTracking:
          type: boolean
        createdAt:
          type: string
          format: date-time
        endedAt:
          type: string
          format: date-time
        description:
          type: string
          example: Designing website for law company.
        duration:
          type: string
          format: duration
          example: 1h
          description: Generates human-readable duration of timeblock.
      required:
        - user
        - isTracking
        - createdAt
      x-examples:
        example-1:
          _id: 1f704bc5-5055-43eb-a851-c87b6b0bf7b9
          user: jay
          isTracking: true
          createdAt: '2019-08-24T14:15:22Z'
          endedAt: '2019-08-24T14:15:22Z'
          description: Designing website for law company.
          duration: 1h
